### PR TITLE
New feats

### PR DESCRIPTION
**Pull request by odanoburu**
- [x] use nosense
- [x] prevent user from assigning man without senses
- [x] index parts of collocations
- [x] add ignore command
- [x] add unsure command
- [x] add confidence/unsure as a field
- [x] transform purposefully_ignored to man/auto with low confidence
- [x] confidence may be colored
- [x] purposefully ignored -> tag-nosense
- [x] add metadata from XML to plists
- [x] don't modify lemma when annotating sense

### CODE REVIEW

**Comment by arademaker** [comment]
What you mean by don’t modify lemmas? We can still edit the lemmas right ?

**Comment by odanoburu** [comment]
when a user assigned a sense I'd add a new lemma corresponding to the new sense (if it wasn't there beforehand).

yes, of course

**Comment by arademaker** [comment]
How Dan that happen before? If the token don’t have a lemma being annotated, how you were listing the gloss ?

**Comment by arademaker** [comment]
You must block a user to add a sense if the sense lemma is not part of the lemmas of that token. In that case the user must first fix the lemmas , right ?

**Comment by odanoburu** [comment]
> How can that happen before? If the token don’t have a lemma being annotated, how you were listing the gloss ?

it might have been the case that the lemma was simply `living`; when the user adds a noun sense, I added  `living%1` to the lemma

> You must block a user to add a sense if the sense lemma is not part of the lemmas of that token. In that case the user must first fix the lemmas , right ?

this happens, and is correct

**Pull request merged**
